name: Generate Podcast Feed
on: [push]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: 3.14.0
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Run Feed Generator
        run: python feed.py
      - name: Push Repo
        run: |
          git config user.name github_action
          git config user.email github_action@mayukhs1.github.io
          git add .
          git commit -m "Modified Feed"
          git push
        
          
      
